### ISSUE TITLE
Please delete repo (https://github.com/tricardojames/tricardojames.github.io) then follow the steps again

### ISSUE THREAD

**Issue by lzblack** [tricardojames/WebTechProject#1]
Steps: [OIM3690/resources@main/Connect-GitHub-Pages-to-Your-Domain.md](https://github.com/OIM3690/resources/blob/main/Connect-GitHub-Pages-to-Your-Domain.md?rgh-link-date=2022-10-28T17%3A40%3A30Z)

**Comment by lzblack** [comment]
Please address this issue. Your website has not been published correctly yet.

**Comment by tricardojames** [comment]
I did what you said and my website still won't load not sure what else I should do

**Comment by lzblack** [comment]
The website is actually on (https://www.dogzz.me/index3.html). You need to change the filename to index.html

**Comment by tricardojames** [comment]
I got it to work now, thank you

**Comment by tricardojames** [comment]
fixed problem
